// 由 schemas/public-v1.schema.json 生成；请勿手改。
export type Subtrack = { "id": string; "name": string; };
export type Industry = { "id": string; "name": string; "subtracks": Array<Subtrack>; };
export type EvidenceRef = { "id": string; "revision_id": string; "quote": string; };
export type Evidence = { "id": string; "revision_id": string; "source": string; "url": string; "title": string; "excerpt": string; "role": string; "observed_at": string | string; "published_at": string | string | null; "date_confidence": string; };
export type AIValue = { "status": "hypothesis" | "supported" | "disproven" | "unknown"; "baseline": string; "capability": string; "user_benefit": string; "incremental_advantage": string; "evidence_refs": Array<EvidenceRef>; };
export type Item = { "id": string; "revision_id": string; "title": string; "summary": string; "industry_ids": Array<string>; "subtrack_ids": Array<string>; "target_user": string; "job_to_be_done": string; "wedge": string; "stage": "hypothesis" | "observed_need" | "candidate" | "regional_hypothesis"; "evidence_tier": null | "A" | "B" | "R"; "ai_value": AIValue; "evidence_refs": Array<EvidenceRef>; "missing_evidence": Array<string>; "next_action": string; "publication_status": "published" | "withdrawn"; "updated_at": string; "origin_lead_id": string | null; "promoted_to": string | null; "source_run_ids": Array<string>; "last_source_run_id": string; };
export type Coverage = { "industry_id": string; "status": string; "material_count": number; "reviewed_count": number; "recent_demand_count": number; "commercial_evidence_count": number; "counterevidence_count": number; "unreviewed_count": number; "missing_dimensions": Array<string>; "exhaustive": false; };
export type Quality = { "coverage_incomplete": boolean; "omitted_evidence_count": number; "withheld_item_count": number; "market_validated": false; "review_summary"?: ReviewSummary; };
export type ListItem = { "id": string; "revision_id": string; "title": string; "summary": string; "industry_ids": Array<string>; "stage": "hypothesis" | "observed_need" | "candidate" | "regional_hypothesis"; "evidence_tier": null | "A" | "B" | "R"; "publication_status": "published" | "withdrawn"; "source_run_ids": Array<string>; "last_source_run_id": string; };
export type PublicDataset = { "contract_version": string; "dataset_id": string; "revision": string; "as_of": string; "generated_at": string; "taxonomy_version": string; "industries": Array<Industry>; "items": Array<Item>; "evidence": Array<Evidence>; "coverage": Array<Coverage>; "quality": Quality; "extensions": { [key: string]: unknown; }; "view": "full"; "snapshot_scope": "research_run" | "site_catalog"; "source_runs": Array<SourceRun>; "site_manifest": SiteManifest | null; };
export type PublicIndex = { "contract_version": string; "dataset_id": string; "revision": string; "as_of": string; "generated_at": string; "taxonomy_version": string; "industries": Array<Industry>; "items": Array<ListItem>; "coverage": Array<Coverage>; "quality": Quality; "extensions": { [key: string]: unknown; }; "view": "index"; "snapshot_scope": "research_run" | "site_catalog"; "source_runs": Array<SourceRun>; "site_manifest": SiteManifest | null; };
export type PublicDetail = { "contract_version": string; "dataset_id": string; "revision": string; "as_of": string; "generated_at": string; "taxonomy_version": string; "industries": Array<Industry>; "items": Array<Item>; "evidence": Array<Evidence>; "coverage": Array<Coverage>; "quality": Quality; "extensions": { [key: string]: unknown; }; "view": "detail"; "snapshot_scope": "research_run" | "site_catalog"; "source_runs": Array<SourceRun>; "site_manifest": SiteManifest | null; };
export type SourceRun = { "run_id": string; "as_of": string; "generated_at": string; "report_sha256": string; };
export type SiteTombstone = { "id": string; "run_id": string; "as_of": string; "reason": "explicit_withdrawal" | "withheld" | "scope_excluded"; };
export type SiteManifest = { "source_run_count": number; "published_count": number; "withdrawn_count": number; "retained_from_history_count": number; "latest_run_id": string; "coverage_basis": "latest_research_run"; "tombstones": Array<SiteTombstone>; "scope_removed_ids": Array<string>; };
export type ReviewSummary = { "source_run_id": string; "evidence_count": number; "reviewed_count": number; "unreviewed_count": number; };
export type PublicDocument = PublicDataset | PublicIndex | PublicDetail;
